Web/RentCars.Web/Controllers/CarsController.cs
namespace RentCars.Web.Controllers
{
    using System.Linq;

    using Microsoft.AspNetCore.Mvc;
    using RentCars.Services.Data;
    using RentCars.Web.ViewModels.Cars;
    using RentCars.Web.ViewModels.Home;

    public class CarsController : BaseController
    {
        private readonly ICarsService carsService;

        public CarsController(ICarsService carsService)
        {
            this.carsService = carsService;
        }

        public IActionResult All(int id = 1)
        {
            const int ItemsPerPage = 6;
            var viewModel = new CarsLstinViewtModel
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                CarsCount = this.carsService.GetCount(),
                Cars = this.carsService.GetAll(id, ItemsPerPage),
            };

            return this.View(viewModel);
        }

        [HttpPost]
        public IActionResult Available(SearchCarsViewModel model)
        {
            if (!this.User.Identity.IsAuthenticated)
        {
                return this.Redirect("/Identity/Account/Login");
            }

            if (!this.ModelState.IsValid)
               {
               return this.RedirectToAction("Index", "Home");
            }

            var cars = this.carsService.GetAvailableCars(model.Pickup, model.Return, model.PickupPlace).ToList();

            var viewModel = new AvailableCarsViewModel
            {
                Cars = cars,
                Start = model.Pickup,
                End = model.Return,
                Days = (model.Return.Date - model.Pickup.Date).TotalDays,

                PickUpPlace = model.PickupPlace,
                ReturnPlace = model.PickupPlace,
            };

            return this.View(viewModel);
        }

        public IActionResult Details(int id)
        {
            const int ItemsPerPage = 1;
            var viewModel = new CarsLstinViewtModel
            {
                Cars = this.carsService.GetAll(id, ItemsPerPage),
            };

            return this.View(viewModel);
        }
    }
}

Web/RentCars.Web/Controllers/OrdersController.cs
namespace RentCars.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using RentCars.Data.Models;
    using RentCars.Services.Data;
    using RentCars.Web.ViewModels.Orders;

    public class OrdersController : BaseController
    {
        private readonly IOrdersService ordersService;
        private readonly ICarsService carsService;
        private readonly UserManager<ApplicationUser> userManager;

        public OrdersController(
            ICarsService carsService,
            IOrdersService ordersService,
            UserManager<ApplicationUser> userManager)
        {
            this.carsService = carsService;
            this.ordersService = ordersService;
            this.userManager = userManager;
        }

        [Authorize]
        public IActionResult MyOrders()
        {
            var viewModel = new AllOrderInputViewModel
            {
                Orders = this.ordersService.All(),
            };

            return this.View(viewModel);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Preview(OrderPreviewInputModel inputModel)
        {
            return this.View(inputModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Order(OrderInputViewModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction("Index", "Home");
            }

            var result = await this.ordersService.MakeOrder(this.User.Identity.Name, inputModel.Id, inputModel.PickUpPlace, inputModel.ReturnPlace, inputModel.Price, inputModel.PickUp, inputModel.Return);
            var carModel = this.carsService.GetCarModelById(id: inputModel.Id);
            var days = (inputModel.Return - inputModel.PickUp).Days;

            return this.RedirectToAction(nameof(this.MyOrders));
        }

        [Authorize]
        public IActionResult Details(string id)
        {
            var viewModel = new OrdersDetailsViewModel
            {
                Cars = this.ordersService.GetOrderById(id),
            };

            return this.View(viewModel);
        }
    }
}

Web/RentCars.Web/Controllers/ReviewsController.cs
namespace RentCars.Web.Controllers
{
    public class ReviewsController : BaseController
    {
    }
}

Web/RentCars.Web/Views/Orders/Details.cshtml
@model RentCars.Web.ViewModels.Orders.OrdersDetailsViewModel

@{ ViewData["Title"] = "Order Details"; }

@foreach (var order in Model.Cars)
{ 

@*@if (Model.ReviewId == null && Model.Status == RentCars.Data.Models.Enums.OrderStatus.Finished)
    {
    <div class="alert alert-dismissible alert-success" style="margin-top:2%">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <h4 class="alert-heading">Congratulations! Your order was finished</h4>
        <p class="mb-0">You can leave a review for your order and win a discount voucher! <a asp-controller="Reviews" asp-action="Create" asp-route-orderId="@Model.Id">Follow this link!</a></p>
    </div>}*@


@*@if (User.IsInRole(GlobalConstants.AdministratorRoleName))
    {
    <a class="btn btn-info" asp-controller="Orders" asp-area="Administration" asp-action="Edit" asp-route-id="@Model.Id">Edit Order</a>}

    @if (@Model.Status == RentCars.Data.Models.Enums.OrderStatus.Active)
    {
    <span class="badge badge-pill badge-warning" style="margin-top:5%">@Model.Status</span> }
                else if (@Model.Status == RentCars.Data.Models.Enums.OrderStatus.Finished)
                {
    <span class="badge badge-pill badge-success" style="margin-top:5%">@Model.Status</span> }
                else
                {
    <span class="badge badge-pill badge-danger" style="margin-top:5%">@Model.Status</span>}

    <span class=" badge badge-pill badge-info" style="margin-top:5%; float:right" onclick="myFunction()">Print this order</span>

    <h1>Order ID: @Model.Id.ToUpper()</h1>*@

<hr class="border-primary" />
<div class="container-fluid">
    <div class="d-flex justify-content-between">
        <h4>Customer Email:</h4>
        <h4>@order.Email</h4>
    </div>
    <hr class="border-primary" />
    <div class="d-flex justify-content-between">
        <h4>Pick Up Location:</h4>
        <h4>@order.PickUpLocation</h4>
    </div>
    <div class="d-flex justify-content-between">
        <h4>Return Location:</h4>
        <h4>@order.ReturnLocation</h4>
    </div>
    <hr class="border-primary" />
    <div class="d-flex justify-content-between">
        <h4>Rent start:</h4>
        <h4>@order.RentStart.ToShortDateString()</h4>
    </div>
    <div class="d-flex justify-content-between">
        <h4>Rent end:</h4>
        <h4>@order.RentEnd.ToShortDateString()</h4>
    </div>
    <hr class="border-primary" />
    <h2>Your Car:</h2>
    <div class="d-flex justify-content-between">
        <img src="@order.Image" alt="Image" width="150"/>
        <div>
            <h4>Model: @order.CarModel</h4>
            <h4>Gear Type: @order.CarGearType</h4>
            <h4>Year: @order.Year</h4>
        </div>
    </div>
    <div>@order.Description.ToString()</div>
    <hr class="border-primary" />
</div>
<center>
    <div class="text-success" style="font-size:200%">Price: $@order.Price</div>
</center>


@if (order.Comment != null)
{
<hr class="border-primary" />
                <div class="justify-content-between">
                    <h3>Your Feedback:</h3>
                    <h4>@order.Comment <strong class="text-primary">Rating: @order.Rating</strong></h4>
                </div>}
}

<hr class="border-primary" />
<script>
    function myFunction() {
        window.print();
    }</script>

Web/RentCars.Web/Views/Orders/MyOrders.cshtml
@model RentCars.Web.ViewModels.Orders.AllOrderInputViewModel

@{ ViewData["Title"] = "My Orders"; }

<center>
    <h1 style="margin-top:2%">
        My Orders
    </h1>
</center>
<hr class="border-info" />



<table class="table table-hover border" name="allorders" id="allorders">
    <thead>
        <tr class="table-primary ">
            <th scope="col">Order Id</th>
            <th scope="col">Car Model</th>
            <th scope="col">Pick Up Location</th>
            <th scope="col">Return Location</th>
            <th scope="col">Start Date</th>
            <th scope="col">End Date</th>
            <th scope="col">Price</th>
            <th scope="col">Status</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var order in Model.Orders)
        {
            if (order.Status.ToString() == "Canceled")
            {
@Html.Raw(" <tr class=\"table-danger\">") }
else if (order.Status.ToString() == "Finished")
{
@Html.Raw(" <tr class=\"table-success\">") }
else
{
@Html.Raw(" <tr class=\"table-warning\">") }
            <tr>
<th scope="row"><a href="/orders/details/@order.Id">@order.Id.ToUpper()</a></th>
                                               <td>
                                    @order.CarModel
                            </td>
                            <td>@order.PickUpLocation</td>
                                            <td>@order.ReturnLocation</td>
                                                            <td>@order.RentStart.ToShortDateString()</td>
                                                                            <td>@order.RentEnd.ToShortDateString()</td>
                                                                                            <td>$@order.Price</td>
                                                                                                            <td>
                                                                                                                @order.Status.ToString()
                                                                                                            @if (order.ReviewId > 0)
                                                                                                            {
                                                                                            <img src="/Images/feedback-given.jpg.png" width="25px" heigth="25px" title="Feedback is given" />}
                                                                                                        </td> </tr>
                                                                                                                                        @Html.Raw(" </tr>")}
        </tbody>
    </table>

    @if (Model.Orders.Count() > 0)
    {
        var spent = this.Model.Orders.Sum(x => x.Price);
<h3 class="text-info">Total spent: $ @spent</h3>}

Web/RentCars.Web/Views/Orders/Preview.cshtml
@model RentCars.Web.ViewModels.Orders.OrderPreviewInputModel

@{ ViewData["Title"] = "Preview"; }

<h1>Hello</h1>


<div class="container-fluid col-md-10 border-danger" style="margin-top: 4%">

    <h3><strong>Dear, @User.Identity.Name</strong></h3>
    <h2><strong>Your order preview:</strong></h2>
    <hr />
    <div class="mx-auto">
        <div class="receipt-id-handler d-flex justify-content-between">
            <h3>Car Model:</h3>
            <h3>@Model.Model</h3>
        </div>
        <hr />
        <div class="d-flex justify-content-between">
            <h4>Rent start:</h4>
            <h4>@Model.RentStart.ToShortDateString()</h4>
        </div>
        <div class="d-flex justify-content-between">
            <h4>Rent end:</h4>
            <h4>@Model.RentEnd.ToShortDateString()</h4>
        </div>
        <hr />
        <div class="d-flex justify-content-between">
            <h4>Price per day:</h4>
            <h4>$@Model.PricePerDay</h4>
        </div>
        @if (@Model.DiscountPercent > 0)
        {
            <div class="d-flex justify-content-between">
                <h4>Price for @Model.Days days:</h4>
                <h4>$@Model.PriceWithoutDiscount</h4>
            </div>
            <div class="d-flex justify-content-between" style="color:red">
                <h4>Discount:</h4>
                <h4>- $@Model.DiscountSum.ToString("F")</h4>
            </div>}

        <div class="d-flex justify-content-between">
            <h4>Total Price:</h4>
            <h4>$@Model.TotalPrice.ToString("F")</h4>
        </div>
        <hr />
        <div class="d-flex justify-content-between">
            <h4>You can pick up your car from <strong>@Model.PickUpPlace</strong>, and return it to <strong>@Model.ReturnPlace</strong>, until the end of <strong>@Model.RentEnd.ToShortDateString()</strong>.</h4>
        </div>



     

    </div>
</div>

<center>
    <div class="d-flex justify-content-around">
        <form asp-controller="Cars" asp-action="Available" method="POST">
            <input type="hidden" value="@Model.ReturnPlace" name="ReturnPlace" />
            <input type="hidden" value="@Model.PickUpPlace" name="PickupPlace" />
            <input type="hidden" value="@Model.RentStart" name="Pickup" />
            <input type="hidden" value="@Model.RentEnd" name="Return" />
            <br />
            <button type="submit" class="btn btn-danger">Cancel</button>
        </form>
        <form asp-controller="Orders" asp-action="Order" method="POST">
            <input type="hidden" value="@Model.ReturnPlace" name="ReturnPlace" />
            <input type="hidden" value="@Model.PickUpPlace" name="PickupPlace" />
            <input type="hidden" value="@Model.RentStart" name="Pickup" />
            <input type="hidden" value="@Model.RentEnd" name="Return" />
            <input type="hidden" value="@Model.Id" name="Id" />
            <input type="hidden" value="@Model.TotalPrice" name="Price" />
            <br />
            <button type="submit" class="btn btn-success">Confirm</button>
        </form>
    </div>
</center>